---
- name: backend server
  hosts: backend
  become: yes
  tasks:
    - name: disabling nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    - name: enabling nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y 
    - name: installing nodejs
      ansible.builtin.package:
        name: nodejs
        state: present
    - name: create user expense
      ansible.builtin.user:
        name: expense
        comment: user add
    - name: creating app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: downloading the content
      ansible.builtin.get_url:
        url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    - name: Unzipping code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes
    - name: install dependencies
      community.general.npm:
        path: /app
    - name: copy backend service content
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: install mysql server
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: check if schema is loaded or not
      ansible.builtin.shell: mysql -h 54.82.90.106 -uroot -pExpenseApp@1 < /app/schema/backend.sql
      register: backend_output
    - name: restarting the server
      ansible.builtin.service:
        name: nodejs
        state: started
        enabled: true
    