---
- name: backend server
  hosts: backend
  become: yes
  tasks:
    - name: disabling nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    - name: enabling nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y 
    - name: installing nodejs
      ansible.builtin.service:
        name: nodejs
        state: present
    - name: create user expense
      ansible.builtin.user:
        name: expense
        comment: user add
    - name: creating app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: downloading the content
      ansible.builtin.get_url:
        url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
    - name: Unzipping code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes
    - name: install dependencies
    