---
- name: "database server"
  hosts: mysql
  becomes: yes
  tasks:
    - name: "Installing mysql server"
      ansible.builtin.package:
        name: "Mysql"
        state: present
    - name: "Start and enable mysql server"
      ansible.builtin.service:
        name: "Mysql"
        state: started
        enabled: yes
    - name: "Setting root password"
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
      